//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextWebServiceClient.textWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://northwindtraders.com/", ConfigurationName="textWebService.WebTextWebServiceSoap")]
    public interface WebTextWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name inputString from namespace http://northwindtraders.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://northwindtraders.com/ToUpper", ReplyAction="*")]
        TextWebServiceClient.textWebService.ToUpperResponse ToUpper(TextWebServiceClient.textWebService.ToUpperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://northwindtraders.com/ToUpper", ReplyAction="*")]
        System.Threading.Tasks.Task<TextWebServiceClient.textWebService.ToUpperResponse> ToUpperAsync(TextWebServiceClient.textWebService.ToUpperRequest request);
        
        // CODEGEN: Generating message contract since element name inputString from namespace http://northwindtraders.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://northwindtraders.com/ToLower", ReplyAction="*")]
        TextWebServiceClient.textWebService.ToLowerResponse ToLower(TextWebServiceClient.textWebService.ToLowerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://northwindtraders.com/ToLower", ReplyAction="*")]
        System.Threading.Tasks.Task<TextWebServiceClient.textWebService.ToLowerResponse> ToLowerAsync(TextWebServiceClient.textWebService.ToLowerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToUpperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToUpper", Namespace="http://northwindtraders.com/", Order=0)]
        public TextWebServiceClient.textWebService.ToUpperRequestBody Body;
        
        public ToUpperRequest() {
        }
        
        public ToUpperRequest(TextWebServiceClient.textWebService.ToUpperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://northwindtraders.com/")]
    public partial class ToUpperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputString;
        
        public ToUpperRequestBody() {
        }
        
        public ToUpperRequestBody(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToUpperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToUpperResponse", Namespace="http://northwindtraders.com/", Order=0)]
        public TextWebServiceClient.textWebService.ToUpperResponseBody Body;
        
        public ToUpperResponse() {
        }
        
        public ToUpperResponse(TextWebServiceClient.textWebService.ToUpperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://northwindtraders.com/")]
    public partial class ToUpperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ToUpperResult;
        
        public ToUpperResponseBody() {
        }
        
        public ToUpperResponseBody(string ToUpperResult) {
            this.ToUpperResult = ToUpperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToLowerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToLower", Namespace="http://northwindtraders.com/", Order=0)]
        public TextWebServiceClient.textWebService.ToLowerRequestBody Body;
        
        public ToLowerRequest() {
        }
        
        public ToLowerRequest(TextWebServiceClient.textWebService.ToLowerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://northwindtraders.com/")]
    public partial class ToLowerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string inputString;
        
        public ToLowerRequestBody() {
        }
        
        public ToLowerRequestBody(string inputString) {
            this.inputString = inputString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToLowerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToLowerResponse", Namespace="http://northwindtraders.com/", Order=0)]
        public TextWebServiceClient.textWebService.ToLowerResponseBody Body;
        
        public ToLowerResponse() {
        }
        
        public ToLowerResponse(TextWebServiceClient.textWebService.ToLowerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://northwindtraders.com/")]
    public partial class ToLowerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ToLowerResult;
        
        public ToLowerResponseBody() {
        }
        
        public ToLowerResponseBody(string ToLowerResult) {
            this.ToLowerResult = ToLowerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebTextWebServiceSoapChannel : TextWebServiceClient.textWebService.WebTextWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebTextWebServiceSoapClient : System.ServiceModel.ClientBase<TextWebServiceClient.textWebService.WebTextWebServiceSoap>, TextWebServiceClient.textWebService.WebTextWebServiceSoap {
        
        public WebTextWebServiceSoapClient() {
        }
        
        public WebTextWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebTextWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebTextWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebTextWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextWebServiceClient.textWebService.ToUpperResponse TextWebServiceClient.textWebService.WebTextWebServiceSoap.ToUpper(TextWebServiceClient.textWebService.ToUpperRequest request) {
            return base.Channel.ToUpper(request);
        }
        
        public string ToUpper(string inputString) {
            TextWebServiceClient.textWebService.ToUpperRequest inValue = new TextWebServiceClient.textWebService.ToUpperRequest();
            inValue.Body = new TextWebServiceClient.textWebService.ToUpperRequestBody();
            inValue.Body.inputString = inputString;
            TextWebServiceClient.textWebService.ToUpperResponse retVal = ((TextWebServiceClient.textWebService.WebTextWebServiceSoap)(this)).ToUpper(inValue);
            return retVal.Body.ToUpperResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TextWebServiceClient.textWebService.ToUpperResponse> TextWebServiceClient.textWebService.WebTextWebServiceSoap.ToUpperAsync(TextWebServiceClient.textWebService.ToUpperRequest request) {
            return base.Channel.ToUpperAsync(request);
        }
        
        public System.Threading.Tasks.Task<TextWebServiceClient.textWebService.ToUpperResponse> ToUpperAsync(string inputString) {
            TextWebServiceClient.textWebService.ToUpperRequest inValue = new TextWebServiceClient.textWebService.ToUpperRequest();
            inValue.Body = new TextWebServiceClient.textWebService.ToUpperRequestBody();
            inValue.Body.inputString = inputString;
            return ((TextWebServiceClient.textWebService.WebTextWebServiceSoap)(this)).ToUpperAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TextWebServiceClient.textWebService.ToLowerResponse TextWebServiceClient.textWebService.WebTextWebServiceSoap.ToLower(TextWebServiceClient.textWebService.ToLowerRequest request) {
            return base.Channel.ToLower(request);
        }
        
        public string ToLower(string inputString) {
            TextWebServiceClient.textWebService.ToLowerRequest inValue = new TextWebServiceClient.textWebService.ToLowerRequest();
            inValue.Body = new TextWebServiceClient.textWebService.ToLowerRequestBody();
            inValue.Body.inputString = inputString;
            TextWebServiceClient.textWebService.ToLowerResponse retVal = ((TextWebServiceClient.textWebService.WebTextWebServiceSoap)(this)).ToLower(inValue);
            return retVal.Body.ToLowerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TextWebServiceClient.textWebService.ToLowerResponse> TextWebServiceClient.textWebService.WebTextWebServiceSoap.ToLowerAsync(TextWebServiceClient.textWebService.ToLowerRequest request) {
            return base.Channel.ToLowerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TextWebServiceClient.textWebService.ToLowerResponse> ToLowerAsync(string inputString) {
            TextWebServiceClient.textWebService.ToLowerRequest inValue = new TextWebServiceClient.textWebService.ToLowerRequest();
            inValue.Body = new TextWebServiceClient.textWebService.ToLowerRequestBody();
            inValue.Body.inputString = inputString;
            return ((TextWebServiceClient.textWebService.WebTextWebServiceSoap)(this)).ToLowerAsync(inValue);
        }
    }
}
